# This file assumes that all transitions have been evaluated



welfare_trans_optimal_real_workers = zeros(no_taus)
welfare_trans_optimal_real_farmers = zeros(no_taus)
welfare_trans_optimal_real_alt_workers = zeros(no_taus)
welfare_trans_optimal_real_alt_farmers = zeros(no_taus)
for τ_index = 1:no_taus
    welfare_trans_optimal_real_workers[τ_index] = sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy  .* (exp.((V_saved_store_optimal[1:Baseline_parameter.ns_fine,2,τ_index] -V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine]) * (1.0 - Baseline_parameter.β) ) ))  - 1;
    welfare_trans_optimal_real_farmers[τ_index] = sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy)  .* (exp.((V_saved_store_optimal[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2,τ_index] -V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]) * (1.0 - Baseline_parameter.β) ) ))  - 1;        
    # This one is still a bit uncertain on what distribution it should be evaulated - I stick to period 2 distr as that is when V() is evaluated
    welfare_trans_optimal_real_alt_workers[τ_index] = (1 - Baseline_parameter.β)* (sum(distr_store_optimal[1:Baseline_parameter.ns_fine,2,τ_index]./current_worker_pop_store_optimal[2,τ_index]  .* V_saved_store_optimal[1:Baseline_parameter.ns_fine,2,τ_index]) - sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy .*V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine])  ); 
    welfare_trans_optimal_real_alt_farmers[τ_index] = (1 - Baseline_parameter.β)* (sum(distr_store_optimal[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2,τ_index]./(1.0 - current_worker_pop_store_optimal[2,τ_index]) .* V_saved_store_optimal[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2,τ_index]) - sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy).*V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)])  ); 
end

#TODO---   the distr for real_alt is kind of unclear for the transition welfare calculation

welfare_subsidy_b_real_workers = sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy  .* (exp.((V_saved_store_baseline[1:Baseline_parameter.ns_fine,2] -V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine]) * (1.0 - Baseline_parameter.β) ) ))  - 1;
welfare_subsidy_b_real_farmers = sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy)  .* (exp.((V_saved_store_baseline[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2] -V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]) * (1.0 - Baseline_parameter.β) ) ))  - 1;        
welfare_subsidy_b_real_alt_workers = (1 - Baseline_parameter.β)* (sum(stat_distr_subsidy_b[1:Baseline_parameter.ns_fine]./current_worker_pop_subsidy_b .* V_saved_store_baseline[1:Baseline_parameter.ns_fine,2]) - sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy .*V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine])  ); 
welfare_subsidy_b_real_alt_farmers = (1 - Baseline_parameter.β)* (sum(stat_distr_subsidy_b[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_subsidy_b) .* V_saved_store_baseline[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2]) - sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy).*V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)])  ); 

welfare_subsidy_nb_real_workers = sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy  .* (exp.((V_saved_store_trans_nb[1:Baseline_parameter.ns_fine,2] -V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine]) * (1.0 - Baseline_parameter.β) ) ))  - 1;
welfare_subsidy_nb_real_farmers = sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy)  .* (exp.((V_saved_store_trans_nb[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2] -V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]) * (1.0 - Baseline_parameter.β) ) ))  - 1;        
welfare_subsidy_nb_real_alt_workers = (1 - Baseline_parameter.β)* (sum(stat_distr_subsidy_nb[1:Baseline_parameter.ns_fine]./current_worker_pop_subsidy_nb .* V_saved_store_trans_nb[1:Baseline_parameter.ns_fine,2]) - sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy .*V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine])  ); 
welfare_subsidy_nb_real_alt_farmers = (1 - Baseline_parameter.β)* (sum(stat_distr_subsidy_nb[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_subsidy_nb) .* V_saved_store_trans_nb[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2]) - sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy).*V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)])  ); 

welfare_inf_real_workers = sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy  .* (exp.((V_saved_store_trans_infra[1:Baseline_parameter.ns_fine,2] -V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine]) * (1.0 - Baseline_parameter.β) ) ))  - 1;
welfare_inf_real_farmers = sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy)  .* (exp.((V_saved_store_trans_infra[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2] -V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]) * (1.0 - Baseline_parameter.β) ) ))  - 1;        
welfare_inf_real_alt_workers = (1 - Baseline_parameter.β)* (sum(stat_distr_inf[1:Baseline_parameter.ns_fine]./current_worker_pop_inf .* V_saved_store_trans_infra[1:Baseline_parameter.ns_fine,2]) - sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy .*V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine])  ); 
welfare_inf_real_alt_farmers = (1 - Baseline_parameter.β)* (sum(stat_distr_inf[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_inf) .* V_saved_store_trans_infra[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2]) - sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy).*V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)])  ); 

welfare_inf_sp_real_workers = sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy  .* (exp.((V_saved_store_trans_infra_sp[1:Baseline_parameter.ns_fine,2] -V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine]) * (1.0 - Baseline_parameter.β) ) ))  - 1;
welfare_inf_sp_real_farmers = sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy)  .* (exp.((V_saved_store_trans_infra_sp[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2] -V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]) * (1.0 - Baseline_parameter.β) ) ))  - 1;        
welfare_inf_sp_real_alt_workers = (1 - Baseline_parameter.β)* (sum(stat_distr_inf_sp[1:Baseline_parameter.ns_fine]./current_worker_pop_inf_sp .* V_saved_store_trans_infra_sp[1:Baseline_parameter.ns_fine,2]) - sum(stat_distr_no_subsidy[1:Baseline_parameter.ns_fine]./current_worker_pop_no_subsidy .*V_saved_no_subsidy_reshaped[1:Baseline_parameter.ns_fine])  ); 
welfare_inf_sp_real_alt_farmers = (1 - Baseline_parameter.β)* (sum(stat_distr_inf_sp[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_inf_sp) .* V_saved_store_trans_infra_sp[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine),2]) - sum(stat_distr_no_subsidy[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)]./(1.0 - current_worker_pop_no_subsidy).*V_saved_no_subsidy_reshaped[(Baseline_parameter.ns_fine+1):(3*Baseline_parameter.ns_fine)])  ); 


